### PR TITLE
Library updated with new version.

### PR DESCRIPTION
**Pull request by wrteam-vimal**
Library updated with new version.

Reason : Causing many issue due to outdated libraries.

### CODE REVIEW

**Review by unangity — APPROVED** [review]

**Comment by geekygeeky** [comment]
@wilburx9 Can you merge this?

**Comment by wrteam-vimal** [comment]
Sorry sir not getting your point.

WRTeam <https://wrteam.in/> | Follow Instagram
<https://www.instagram.com/wrteam.in/> | Skype Support
<https://join.skype.com/invite/BZ8brCpb7far> | Codecanyon
<https://codecanyon.net/user/wrteam/portfolio>


*Regards,*
*Vimal Gondariya*

**Comment by Ahmed-Sellami** [comment]
We need this. Many other packages depend on http package. And when they support the latest version of http, the project's version solving fails.

**Comment by ify-osakwe** [comment]
The versioning error I am facing in my pubspec file has brought me here.
@unangity @wilburx9 

merging this PR will do a lot of good right now

**Pull request closed without merging**
