### PR TITLE
Converted metadata to json format

### PR DESCRIPTION
**Pull request by Itope84**
The metadata get method in charge.dart currently returns a string , instead of a json object (https://github.com/wilburt/flutter_paystack/blob/master/lib/src/models/charge.dart#L158). 
This is being sent directly to Paystack as seen here(https://github.com/wilburt/flutter_paystack/blob/master/lib/src/api/request/card_request_body.dart#L54)

An example of the currently returned value is this: 
```
'{custom_fields: [{"user_action":"new_card","user_email":"topephysics@gmail.com","mobile_number":"08181634383"}]}'
```

The string itself is useless if you need to perform any operations on it at the backend for example. since you cannot decode the string.

This PR converts the metadata into json by calling `jsonEncode()` from the `dart:convert` library.

calling charge.metadata will now return something of the form 
```
{"custom_fields":[{"user_action":"new_card","user_email":"topephysics@gmail.com","mobile_number":"08181634383"}]}
```

which is valid json format.

### CODE REVIEW

**Comment by Itope84** [comment]
Hi @wilburt 
could you have a look at this please?

**Comment by wilburt** [comment]
I am so sorry for the delay. Thanks for the bug fix.

Also, do you think the method of adding metadata to the `charge` object makes sense? I mean with the `putCustomField` and `putMetaData` functions.

**Comment by Itope84** [comment]
Yeah, I think it makes sense actually. You can add different fields to metadata, hence the `putMetaData` function. But custom_fields is a common field in the metadata, so it makes sense to have a separate `putCustomField` function. I had no difficulty understanding what it does.

**Comment by wilburt** [comment]
Ok great. Thank you.

**Comment by Itope84** [comment]
Hi @nmeri17 , the dev branch probably hasn't been merged into master yet. If you need this urgently, you can download the dev branch (simply download the project in zip format and switch to dev branch), then copy the contents of the lib folder into a folder (preferably named `flutter_paystack`) inside your lib folder.

Then import from that folder instead of from the package. (Remove flutter_paystack from your pubspeck.yaml to avoid confusion during code completion).

In essence:
```dart
import 'package:my_project/utils/flutter_paystack/flutter_paystack.dart'
...

void initState() {
    PaystackPlugin.initialize(publicKey: publicKey);
    super.initState();
 }
```

**Comment by Itope84** [comment]
Do let me know if you have any issues with it

**Comment by nmeri17** [comment]
Thanks for the prompt response. I'll forward to the flutter dev and get back to you

**Comment by wilburt** [comment]
@nmeri17  You might want to upgrade the plugin to `1.0.3+1`, this change has landed in the release.

**Comment by nmeri17** [comment]
I can confirm all is good now. Many thanks

**Pull request merged**
